kind: Deployment
metadata:
  name: yolo
  labels:
    app: yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
        labels:
          app: yolo
    spec:
      containers:
      - name: yolo
        image: amirstudent3232/yolo:100
        env:
          - name: REGION_NAME
            value: "eu-north-1"
          - name: DYNAMO_TABLE
            value: "AmirAWSpro"
          - name: BUCKET_NAME
            value: "sherman3"
          - name: SQS_QUEUE_NAME
            value: "ShermanAWSSQSProject"

